Env: $env
Tag: $tag
AppName: $appName


containers:
  app:
    image:
      pullPolicy: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi
  rproxy:
    image:
      name: aksrao1998/nginx:1.25.3
      pullPolicy: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi

service:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30010


