Env: $env
Tag: $tag
AppName: $appName

replicas: 1

containers:
  app:
    image:
      pullPolicy: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi
  rproxy:

service:
  - port: 3000
