Env: $env
Tag: $tag
AppName: $appName


containers:
  app:
    image:
      pullPolicy: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi
  rproxy:
    image:
      name: "nginx:1.25.3-bookworm"
      pullPolicy: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 500Mi

service:
  type: ClusterIP
  ports:
    - name: http-port
      port: 80
      protocol: TCP
      targetPort: 8080


