name: create manifest files

on:
  workflow_dispatch:
    inputs:
        Environment:
            description: choose an environmment
            type: choice
            default: dev
            options:
              - dev
              - qa
              - prod
        Application:
            description: choose an application
            type: choice
            default: chat-app-be
            options:
              - chat-app-be
              - fe
        TAG:
          description: choose an tag
          type: choice
          default: 20240317071121
          options:
            - 20240317070929
            - 20240317071121

  # repository_dispatch:
  #   types: [app-deploy]
jobs:
  run_if_success:
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.TAG }}
      env: ${{ github.event.inputs.Environment }}
      appName: ${{github.event.inputs.Application}}
    steps: 
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: build the helm chart
        run: helm template $appName-chart ./helm-chart --set Env=$env --set AppName=$appName --set Tag=$TAG -f ./helm-chart/values.yaml -f ./helm-chart/env/$env/values.yaml
      - name: set up test cluster
        uses: docker://kindest/node:v1.23.2
        with:
          args: create cluster --name kind-cluster --config=kind-config.yaml
      - name: Set up kubectl
        uses: azure/kubectl@v1
        with:
          install-context: true
      - name: Configure kubectl
        run: kubectl cluster-info --context kind-kind

      - name: Create Namespaces
        run: |
          kubectl create namespace dev
          kubectl create namespace qa
          kubectl create namespace prod
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'
      - name: Deploy Helm Chart to Dev
        run: helm upgrade --install $appName-chart ./helm-chart --set Env=$env --set AppName=$appName --set Tag=$TAG -f ./helm-chart/values.yaml -f ./helm-chart/env/$env/values.yaml --namespace dev
      - name: Access the Kind Cluster
        run: |
          kubectl cluster-info --context kind-kind
          kubectl get nodes --context kind-kind
          kubectl get pods -n dev --context kind-kind