name: create manifest files

on:
  repository_dispatch:
    types: [app-deploy]
jobs:
  run_if_success:
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.client_payload.tag }}
      env: ${{ github.event.client_payload.env }}
      appName: ${{github.event.client_payload.appName}}
    steps: 
      - name: build the helm chart
        run: |
          echo $TAG
          echo $env
          echo $appName