name: create manifest files

on:
  repository_dispatch:
    types: [app-deploy]
jobs:
  run_if_success:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.client_payload.tag }}
      env: ${{ github.event.client_payload.env }}
      appName: ${{github.event.client_payload.appName}}
    steps: 
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: build the helm chart
        run: helm template ${{github.event.client_payload.appName}}-chart ./helm-chart --set env=${{github.event.client_payload.env} --set appName=${{github.event.client_payload.appName}} --set tag=${{github.event.client_payload.tag}} -f values.yaml