name: pull the image

on:
  repository_dispatch:
    types: [my-pull]
jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps: 
      - name: pull the image
        run: docker pull aksrao1998/chat-app-be:${{github.event.client_payload.tag}}
        IMAGE_NAME=$(docker inspect --format='{{index .RepoDigests 0}}' aksrao1998/chat-app-be:${{github.event.client_payload.tag}}
        echo "Docker image name: $IMAGE_NAME"